### ISSUE TITLE
Cache not flushing completely with Python and C++ functions

### ISSUE THREAD

**Issue by dinhngtu** [faasm/faasm#773] opened 2023-07-17 12:52 UTC
Hello,

I've been trying out the Faasm platform and would like to ask a couple questions concerning caching.

I tried to update a Python function that has already been uploaded but haven't found a way to do it.
When I query the upload service directly, I get the new function code, but if I run the Python function or read its file content (`/pyfuncs/python/test/function.py`), the file contents remain that of the old version.
I've tried various flushing methods (inv func.flush from the cpp container, inv flush.all with faasm-cli, restarting the cluster) without success.
I'd like to know how to flush the cached code of a Python function.

I've also tried C++ functions.
After updating a function, the flushing (with func.flush) works, but only for the first execution of that function.
The second execution of the function reverts to the old code.
I had to restart all workers to completely flush the function.
Is there an alternative method to flush C++ functions without having to restart the worker?

I'm on Faasm 0.9.9 at the moment.

**Comment by csegarragonz** [comment] 2023-07-18 12:33
Hey @dinhngtu , thanks for reporting this and using Faasm!

A lot has changed since 0.9.9 (and some of the documentation is still not up to date), but with the latest set-up I'm not able to reproduce the issues you describe. I can only reproduce an error in Python where, after flushing, sometimes the new function is picked up, and sometimes the old one (but not with C++ functions).

We have changed the way to deploy/interact with a running cluster in favor of [`faasmctl`](https://github.com/faasm/faasmctl). Now, you can test Faasm without having to clone the repo. Please let me know if the following solve your issues (bar the problem with Python flushing, which I will look into).

```bash
# Install faasmctl in a virtual environment
mkdir faasm-test && cd faasm-test;
python3 -m venv venv
source ./venv/bin/activate
pip3 install faasmctl==0.5.6

# Start a Faasm cluster (and export the corresponding env. variable)
faasmctl deploy.compose
export FAASM_INI_FILE=./faasm.ini

# Sanity check (should see all services running)
faasmctl status
```

C++ flushing:

```bash
# Get a CPP client to upload and run C++ functions
faasmctl cli.cpp

# Cross-compile the demo/hello function, upload it to the server, and run it
inv func demo hello func.upload demo hello func.invoke demo hello
# Outputs: Hello Faasm!

# Modify the hello.cpp function
sed -i 's/Hello/Bye/g' ./func/demo/hello.cpp

# Flush the executors
inv func.flush

# Cross-compile again the demo/hello function, upload it to the server, and run it
inv func demo hello func.upload demo hello func.invoke demo hello
# Outputs: Bye Faasm!

# Invoke it again
inv func.invoke demo hello
# Outputs: Bye Faasm!

exit
```

Python flushing:

```bash
# Get a python
faasmctl cli.python

# Cross-compile the CPython runtime and upload it
inv cpython.func cpython.upload

# Upload one python function and invoke it
inv func.uploadpy hello func.invoke python hello

# Modify the hello.cpp function
sed -i 's/Hello/Bye/g' ./func/python/hello.py

exit
```

Annoyingly, there's no `func.flush` in python so we need to do it from `faasmctl` itself.
faasmctl flush.workers

```bash
faasmctl cli.python

# Flush the executors
inv func.uploadpy hello func invoke demo hello
# Outputs with 'Bye'

# However, invoking again indeed uses the old function
inv func invoke demo hello
# Outputs with 'Hello'

exit
```

**Comment by csegarragonz** [comment] 2023-08-28 16:20
I'm gonna close this issue. Please feel free to re-open if the errors persist!

**Closed by csegarragonz** 2023-08-28 16:20 UTC
